apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: jupyterhub-storage
  namespace: jhub
  annotations:
    storageclass.kubernetes.io/is-default-class: "true" #---设置为默认的storageclass
provisioner: jupyterhub # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  archiveOnDelete: "false"
