apiVersion: v1
kind: PersistentVolume
metadata:
  name: gitlab-pg-data
spec:
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  persistentVolumeReclaimPolicy: Recycle
  storageClassName: "gitlab-pg-data"
  nfs:
    # real share directory
    path: /home/azureuser/data/nfs/gitlab/postgresql
    # nfs real ip
    server: 10.240.0.4
