apiVersion: v1
kind: Service
metadata:
  name: nledu-mysql-jhubauth
  namespace: jhubauth
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 31306
  selector:
    app: nledu-mysql-jhubauth
