apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: gitlab-storageclass
  namespace: gitlab
provisioner: gitlab # or choose another name, must match deployment's env PROVISIONER_NAME'
parameters:
  rchiveOnDelete: "false"
